PCA-Based Drift Detection
1) Standardizzare l'intervallo dei valori delle feature iniziali per farle contribuire allo stesso modo all'analisi.
2) Calcolare la matrici di covarianza delle feature dei due data sets (Old and New).
3) Estrarre i vettori degli autovalori associati agli autovettori delle due matrici di covarianza.
4) Il grado di deriva tra l'insieme dei dati New e Old viene calcolato misurando l'angolo di intersezione tra gli autovalori dei due insiemi, cioà la varianza delle componenti principali dei due set di dati.
5) Se l'angolo è >= ALLARME && < DRIFT viene segnalato un allarme, se l'angolo è >= DRIFT viene segnalato un drift.

40° allarme, 50° drift.               in gradi d'arco
0,7 allarme, 0,875 drift.             in radianti

In [152]:
import pandas as pd
import numpy as np
import csv
import skmultiflow as sk
import sklearn.decomposition as dec
import scipy.linalg as lin
size=150
dataset=pd.read_csv('SRdrift.csv' ,usecols=["A","B","C"])
data_stream= sk.data.DataStream(dataset ,y=None, n_targets=0)
data_stream.print_df()
data_stream.prepare_for_use()
 
data=data_stream.next_sample(batch_size=size)[0]
old_w=pd.DataFrame(data, columns=['A','B','C'])
print(f"Old:{old_w}")

[[-258.93763863 -654.19491326 -570.7438663 ]
 [-258.70523191 -655.15165221 -570.92558994]
 [-259.4375307  -653.76023233 -570.98461852]
 ...
 [-258.82138476 -654.07704964 -571.45474237]
 [-259.22645187 -654.94091298 -570.51667721]
 [-259.7429683  -654.39650835 -572.13457074]]
[]
Old:              A           B           C
0   -258.937639 -654.194913 -570.743866
1   -258.705232 -655.151652 -570.925590
2   -259.437531 -653.760232 -570.984619
3   -259.121990 -654.550492 -571.737737
4   -259.557844 -653.905345 -571.012381
..          ...         ...         ...
145 -258.798988 -654.872263 -571.819494
146 -259.473796 -654.991745 -571.522705
147 -259.305697 -654.621364 -571.014293
148 -258.883881 -654.640936 -571.346336
149 -259.249610 -654.842203 -571.043125

[150 rows x 3 columns]


c:\Users\Salvatore Drago\Desktop\progetto_lab\lib\site-packages\skmultiflow\data\base_stream.py:194: FutureWarning: 'prepare_for_use' has been deprecated in v0.5.0 and will be removed in v0.7.0.
New instances of the Stream class are now ready to use after instantiation.
  category=FutureWarning)


In [166]:
data=data_stream.next_sample(batch_size=size)[0]
new_w=pd.DataFrame(data, columns=['A','B','C'])
print(f"New:{new_w}")

New:              A           B           C
0   -259.057466 -654.704487 -572.921370
1   -260.029719 -654.844334 -570.884649
2   -259.045381 -654.098039 -571.250460
3   -258.608910 -653.666116 -570.872913
4   -259.573840 -653.962251 -571.477056
..          ...         ...         ...
145   98.766563   99.875604  -29.183929
146   98.995751   99.785678  -29.427856
147   98.985664   99.782940  -29.302660
148   98.897559   99.992909  -29.277720
149   98.984779   99.919394  -29.467548

[150 rows x 3 columns]


In [167]:
pca_old=dec.PCA(n_components=None, copy=True, whiten=False, svd_solver='auto')
pca_old.fit(old_w)
old_eigenvalues= pca_old.explained_variance_
print(f"OLD eigenvalues: {old_eigenvalues}")


OLD eigenvalues: [6.98529179e+04 1.26851200e+04 2.18518828e-01]


In [168]:
pca_new=dec.PCA(n_components=None, copy=True, whiten=False, svd_solver='auto')
pca_new.fit(new_w)
new_eigenvalues= pca_new.explained_variance_
print(f"NEW eigenvalues: {new_eigenvalues}")

NEW eigenvalues: [315235.11852542  63846.51211114    546.82795949]


In [169]:
v1=np.array([1,3])
v2=np.array([4,2])
print(old_eigenvalues,new_eigenvalues)
print(np.dot(old_eigenvalues,new_eigenvalues))
print((np.dot(old_eigenvalues,new_eigenvalues))/((np.linalg.norm(old_eigenvalues)*np.linalg.norm(new_eigenvalues))))
angolo= np.arccos((np.dot(old_eigenvalues,new_eigenvalues))/((np.linalg.norm(old_eigenvalues)*np.linalg.norm(new_eigenvalues))))

print(angolo)

[6.98529179e+04 1.26851200e+04 2.18518828e-01] [315235.11852542  63846.51211114    546.82795949]
22829993626.443005
0.9997946875763863
0.020264227077794603
